### ISSUE TITLE
Updating for Dawntrail

### ISSUE THREAD

**Issue by Jawsofgoldie** [AsgardXIV/XAT#11]
Absolutely love this plugin but I was wondering if you plan updating it for the new expansion?
Thank you kindly :)

**Comment by Minmoose** [comment]
Yes, I do! Sorry for the long wait,
the XAT Dalamud Plugin has been merged into [Brio](https://github.com/Etheirys/Brio/releases/tag/v0.4.0) 

You can find out how to install Brio [here](https://etheirys-tools.gitbook.io/brio)
