### ISSUE TITLE
Error exporting: Execution failed: Failed to save tagfile

### ISSUE THREAD

**Issue by Bakanarchie** [AsgardXIV/XAT#2]
Hello there!

I am quite new to modding and have been trying out XAT for the first time today while following a tutorial to make sure I don't do anything wrong.

Unfortunately, I have come across an error message at the moment of exporting (after selection the pap file, the sklb file and then clicking on the animation in animation select; then trying to export to fbx) :
"Error exporting: Execution failed: Failed to save tagfile to C:\Users\Théo\AppData\Local\Temp\tmpC114.tmp

I have already tried restarting the computer, or launching XAT as an admin; neither of these options made the error message disappear. 

Is there anything I forgot to do? If not, is there a way I can make this error go away?

**Comment by Bakanarchie** [comment]
Addendum : The error also happens when trying to export to other file formats.

**Comment by asgardkat** [comment]
Can you provide the pap and sklb you are using?
I haven't seen this failure before.

**Comment by Bakanarchie** [comment]
Sure, they will be attached to this reply.
[issue.zip](https://github.com/AsgardXIV/XAT/files/9924917/issue.zip)

**Comment by asgardkat** [comment]
Hmm. I was able to extract those without issue.
Do you definitely have the VS2012 redist installed? You need the x86 version.

It can be grabbed from https://www.microsoft.com/en-ca/download/details.aspx?id=30679

**Comment by Bakanarchie** [comment]
I double checked this as well; I can only uninstall or repair. I'm going to
try reinstalling and I'll keep you posted.

Also, it seems like the files are created under the Temp folder but remain
empty.

**Comment by Bakanarchie** [comment]
After repairing my install, nothing has changed.
Here's a screenshot taken a minute ago of the issue, in-case anything might help you in that.

EDIT : The filename mentionned always changes.
![image](https://user-images.githubusercontent.com/40968190/199628881-01d02fe9-b5eb-420f-b5a4-057e14746232.png)

**Comment by asgardkat** [comment]
Perhaps an antivirus blocking it or something?
Unfortunately I really have no idea as those files extract fine for me

Just confirming that you extracted all the files in the zip? And that you extracted it somewhere to a path with no spaces in it? Like C:\XAT or similar?

You should have: 
```
XAT.exe
XATHavokInterop.exe
WebView2Loader.dll
```

**Comment by Bakanarchie** [comment]
Let me test all of that and come back at you with my results.

**Comment by Bakanarchie** [comment]
Ok here's what I have tried : 
- Unzipping XAT into a different location (C:\XAT\)
- Disabling my anti-virus entirely
- Moving the files to a different location (C:\A\)
- Moving the files to the same location as XAT.exe

All give me the same error (with a different file, of course).

Perhaps is it related to the "é" in my name? I'm going to try on a fresh account later and will give you the results.

**Comment by asgardkat** [comment]
Hmm, yeh, that's possible. The Havok interop stuff might not handle unicode characters in paths correctly.

**Comment by Bakanarchie** [comment]
Alright, the test was very conclusive. In-case anyone gets this error in the future : Remove any special characters from your Windows username. I have tried on a new account named xat with administrator permissions and it worked wonders.

Thank you for your patience & helping me troubleshoot this @AsgardXIV !
